# Generated by scripts/gen-packaging.mjs — do not edit by hand.
# Tap install:
#   brew tap click6067-ship-it/fitllm https://github.com/click6067-ship-it/fitllm-engine
#   brew install fitllm
#
# This is a binary formula. homebrew-core does not accept prebuilt binaries and
# its notability bar for self-submitted projects is 225 stars / 90 forks /
# 90 watchers, which this project does not meet — so a tap is the honest home
# for it today, not a workaround we are hiding.
class Fitllm < Formula
  desc "Will this LLM fit on your GPU or Mac? Architecture-accurate memory estimates"
  homepage "https://fitllm.run"
  version "2.18.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/click6067-ship-it/fitllm-engine/releases/download/v2.18.1/fitllm-v2.18.1-darwin-arm64"
      sha256 "4cb182773f03e59627fad452575be7f561d90402ad89b8f2dd4452800c189e87"
    end
    on_intel do
      url "https://github.com/click6067-ship-it/fitllm-engine/releases/download/v2.18.1/fitllm-v2.18.1-darwin-x64"
      sha256 "97a17f73722fe1fb053238434cc2b5a454e5d72031d83eea086998242314a391"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/click6067-ship-it/fitllm-engine/releases/download/v2.18.1/fitllm-v2.18.1-linux-arm64"
      sha256 "19414b4a0fb3171cb64ef930a2a6468fb2c43de912bb6bb0eaec25340c27b862"
    end
    on_intel do
      url "https://github.com/click6067-ship-it/fitllm-engine/releases/download/v2.18.1/fitllm-v2.18.1-linux-x64"
      sha256 "d9d20e5316c6cccf0b09315247c41e27350ac071328c79558379e48297140aaf"
    end
  end

  def install
    bin.install Dir["*"].first => "fitllm"
  end

  test do
    assert_match "FITS", shell_output("#{bin}/fitllm 'Gemma 4 31b' --gpu 'RTX 5090'")
  end
end
